# Generated by Django 5.2.5 on 2025-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('mystery', 'Mystery'), ('horror', 'Horror'), ('non-fiction', 'Non-Fiction')], max_length=30)),
            ],
        ),
    ]
