# Generated by Django 5.2.5 on 2025-08-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_company_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='com',
        ),
    ]
